name: Sample Service Validator Config Build and Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build-dist:
    runs-on: ubuntu-latest
    steps:
      - name: Check out GitHub Repo
        uses: actions/checkout@v2

      #
      # Set up python
      #
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          cache: 'pip'
      - run: pip install -r requirements.txt

      #
      # Generate the config files
      #
      - name: Validate sources, generate configs, and verify generated configs
        run: make
